### PR TITLE
Use foreground service to manage VPN connection changes

### PR DESCRIPTION
**Pull request by klinker24**
This is the first part in improving the reliability of the app. Please **do not merge** yet, as I just implemented this today and it will require some real world testing to ensure the VPN connection remains active.

The [NetAngelApplication](https://github.com/net-angel/netangel-protection-android/blob/master/app/src/main/java/com/netangel/netangelprotection/NetAngelApplication.java) class was kind of a mess. It was trying to manage the state of the VPN, along with saving a static reference that other parts of the app could pull out.

The static reference for the `Application` can actually be a major issue. It contributes significantly to memory leaks. Android has had this problem since the beginning: https://android-developers.googleblog.com/2009/01/avoiding-memory-leaks.html

The `Application` class will not exist if the app is not in memory. Since the `Application` class was trying to manage and control the state of the VPN, this could potentially be a major problem. With this leak, the app would take significantly more memory, which is something that Android doesn't really like. When the system gets low on memory (or there are long running tasks active), it will start shutting down services and apps that are running in the background. This app would almost certainly get shut down, since it is something that Android sees as always running and the user is not interacting with it at all. When it gets shut down, the app would stop managing the VPN.

So, this PR does two things:
1. Fix the memory leak
2. Move the VPN management to a [foreground service](https://developer.android.com/guide/components/services.html#Foreground)

By specifying that our app is using a foreground service, Android knows that it **should not** get shut down due to memory restrictions. Forcing a foreground service is the only way to guarantee that the background processes are kept alive.

The one downside to foreground services, is that you have to provide a persistent notification for them. I don't really think that this is a downside for this app though, by having the notification active, the user is able to monitor if the app is connected to the VPN or not. This notification doesn't exist in the status bar, but it does exist in the notification panel, when that is opened:

notification

### CODE REVIEW

**Comment by klinker24** [comment]
Been using this all through the weekend, and today. Seems like the VPN has been connected the entire time, have not seen any downtime, and the pornography sites have remained blocked. I am ready to give this one the thumbs up as an initial step to improve reliability.

This will give us a great base to build off of and now that we can be confident that we are always listening to changes in the connection, we can use that to improve consistency and force the user to remain connected, even when they try to manually disconnect.

**Comment by klinker24** [comment]
For another note, I put the original version of the app on my phone tonight, and within the hour, it had already lost connection to the VPN, without notifying me, or trying to reconnect. I would say this change is an immediate improvement over the previous version of the app!

**Comment by eterry1388** [comment]
This is great.  I love the notification in the notification panel.  Not a downside at all.  Do you feel this is ready to merge then?

**Comment by klinker24** [comment]
Yeah I thought that the notification was perfect for this usage as well. It doesn't work for every app, but I think it helps the vision that we have for this app.

Yep, this should be ready to merge now!

**Comment by klinker24** [comment]
I have made a few edits to the `/app/build.gradle`, and notes in the `/build_instructions` folder, to safely - for an open-source project - apply the release build configurations, without checking the sensitive files into version control.

I just added it to this PR, since I had already thrown the build instructions on here.

**Pull request merged**
