### PR TITLE
Connection Requests

### PR DESCRIPTION
**Pull request by klinker24**
This PR handles #30 and #21, which are both issues around managing the connection.

For #30, I went with the second option discussed there, just to get started with something and see if there are more reports of this. After the VPN connection gets reset, it will wait 2 mins before connecting again.

So, when the user goes from LTE -> WiFi, LTE -> No signal, etc., the app will wait 2 mins for the connection to stabilize, before reconnecting. This is all managed in the persistent `VpnStateService`.

--- 

For #21, I created the `NetAngelConnectionCheck`. It will get the devices external IP address from `https://api.ipify.org?format=json`, then use some internal Java classes (`InetAddress`) to pull out the host name.

If that host name contains "netangel", then we know we are on the NetAngel VPN. If not, then the connection is restarted after 2 mins, as with the last fix.

### CODE REVIEW

**Comment by eterry1388** [comment]
What if there is no internet? When it attempts to reach `api.ipify.org`, it would fail and restart the VPN connection.  Should there be the concept of a retry on that api call?

So if it can't reach the endpoint, it would wait a few seconds and retry.  If it gets back an IP that is not on the NetAngel VPN it would wait a few seconds and retry.  Maybe after a certain number of retries, it will then restart the VPN.

What are your thoughts?

**Comment by klinker24** [comment]
We can make a system of retries, definitely. 

Currently, if it fails or is not on the NetAngel VPN, it will wait 2 mins, restart the connection, then check again

**Comment by eterry1388** [comment]
So while it is waiting those 2 minutes, if it happens to get back on the NetAngel VPN, does it know not to restart the connection?

**Comment by klinker24** [comment]
No, it would still restart it. Would be easy to stop that though, I will add that in a bit. 

Since we are still listening for connecting changes, we can just cancel the timeout so that it doesn't restart

**Pull request merged**
