### PR TITLE
Onboarding + Device Admin

### PR DESCRIPTION
**Pull request by klinker24**
This is discussed, along with some screenshots of the process, in #10.

This is currently marked as *WIP* because I am not sure how you want me to notify the accountability partners if the user disables it as a device administrator.

These are the [APIs](https://github.com/klinker24/netangel-protection-android/blob/master/app/src/main/java/com/netangel/netangelprotection/restful/RestfulApi.java#L127) that are currently visible in the Android app.

Finishing this one should be as easy as adding another `Retrofit` API, on the Android side, but I am not sure what all is required on the backend, or if something new will need to be made.

Also, feel free to give some suggestions for the wording, on the dialogs.

main activity

### CODE REVIEW

**Comment by eterry1388** [comment]
@klinker24 Is this ready? Is there more you are waiting on from me?

**Comment by klinker24** [comment]
No, I am not done just yet, got the intro activity stuff (#25) started, but I need to refine it a little bit and clean it up first. Will post some screenshots tomorrow!

**Comment by eterry1388** [comment]
Oh nice! Didn't realize you were including that in this. But that is fine. After this and the other open pull request is merged, do you feel it will be ready for another release?

**Comment by klinker24** [comment]
I finished up with the first iteration of the onboarding/intro wizard tonight: https://youtu.be/2S3CnKxPW8w

Let me know what you think, and how you want it tweaked. It is very similar to how other apps do onboarding, with Material Design. This one will force the user to enable the device admin functionality, and have them turn on the VPN. Colors are an especially easy thing to change, if you have suggestions for other colors for it, or if you want me to take out the fade animation between the different colors and just have it go from one color to the next. Whatever works, just let me know what variations you guys want to try!

For a release: yes! Once we get this merged in (and #31), we should be ready to cut the next version of the app 👍

**Comment by eterry1388** [comment]
I like it a lot.  Very smooth Material Design is cool.  This will be good to add to as we need to. For instance in the future, I can see the first step having the option of choosing if the device is a for protecting (for a kid's device) or for administrating (for a parent's device).  @brnmckllr want to change the onboarding in any way?

**Comment by brnmckllr** [comment]
Looks really smooth. Really, I just want to make sure it is self guiding to naturally lock everything down. And then give the option later to disable stuff as needed. A lot of our users would like that.

**Comment by klinker24** [comment]
For me, it is very self guiding, there is really only one button that they can press when they get to the screens, without going through those steps, there isn't anything they can do. If you would like, I can remove that requirement though, or I could tell them at some point, "go ahead and enable these now, you can always turn them off later"

When they get past the initial pager, and onto the normal activity, with the toggles, they can do everything there, and disable the VPN or the device admin, that they had to disable on the intro activity.

It is pretty easy to take out the lock-down feature, though. Maybe you guys would like me to build a version of each (locked-down on the intro activity, and not locked-down), and see which you like better?

**Comment by klinker24** [comment]
I added the device name page to the intro, it isn't quite done though, the app needs to be able to tell the backend that the user is trying to change the device name. I made some comments here about how it works: https://github.com/net-angel/netangel-protection-android/issues/33

**Comment by klinker24** [comment]
This should be completely done now. I went ahead and changed the first page to have a white background, to match the rest of the app (#33)
.
I have also implemented the new API to update the device name and confirmed that it is working as expected!

**Pull request merged**
